# Generated by Django 4.2.3 on 2023-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_remove_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
    ]
