# Generated by Django 4.2.3 on 2023-08-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_userprofile_email_alter_userprofile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
