# Generated by Django 4.2.3 on 2023-09-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_newprofile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newprofile',
            name='password',
        ),
    ]
